// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGFbDZBQ0AbdZ3YLOx6Mv18niqqwLeiQ',
    appId: '1:119481246576:web:45717266a786417cb625b5',
    messagingSenderId: '119481246576',
    projectId: 'pocketfm-2024',
    authDomain: 'pocketfm-2024.firebaseapp.com',
    storageBucket: 'pocketfm-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMhivtC6Inn2pkk8KmWPs01zTKhiQy-tk',
    appId: '1:119481246576:android:394fa9897d21c3eeb625b5',
    messagingSenderId: '119481246576',
    projectId: 'pocketfm-2024',
    storageBucket: 'pocketfm-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKDuOxU3H6oVvEiNpEzFVa2OOTC8MTUk',
    appId: '1:119481246576:ios:4291b680856e3f66b625b5',
    messagingSenderId: '119481246576',
    projectId: 'pocketfm-2024',
    storageBucket: 'pocketfm-2024.appspot.com',
    iosBundleId: 'com.divinetechs.dtpocketfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsKDuOxU3H6oVvEiNpEzFVa2OOTC8MTUk',
    appId: '1:119481246576:ios:4291b680856e3f66b625b5',
    messagingSenderId: '119481246576',
    projectId: 'pocketfm-2024',
    storageBucket: 'pocketfm-2024.appspot.com',
    iosBundleId: 'com.divinetechs.dtpocketfm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpGFbDZBQ0AbdZ3YLOx6Mv18niqqwLeiQ',
    appId: '1:119481246576:web:fb9b5530d4919264b625b5',
    messagingSenderId: '119481246576',
    projectId: 'pocketfm-2024',
    authDomain: 'pocketfm-2024.firebaseapp.com',
    storageBucket: 'pocketfm-2024.appspot.com',
  );
}
